package vgu.dz.tvelth.FrameMain;




import vgu.dz.tvelth.DrawRec;
import vgu.dz.myfuncs.MyMath;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.Objects;


public class FrameMain extends JFrame {
    private JPanel panelMain;
    private JButton saveButton;
    private JButton drawButton;
    private JLabel picLabel;
    private JTextField sizeTextField;
    private JPanel panel;
    private JLabel depthRecursionLabel;

    public FrameMain() {
        this.setTitle("Рисовалка");
        this.setContentPane(panelMain);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();


        drawButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage image = DrawRec.drawRecursion(MyMath.isNumber(sizeTextField.getText())  ? Integer.parseInt(sizeTextField.getText()) : 3);
                DrawRec.setImage(image, picLabel);
            }
        });
        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage image = DrawRec.drawRecursion(MyMath.isNumber(sizeTextField.getText())  ? Integer.parseInt(sizeTextField.getText()) : 3);
                DrawRec.savePicture("out.png",image);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
